### ISSUE TITLE
SiameseXML results reproduction

### ISSUE THREAD

**Issue by nbcc** [Extreme-classification/GalaXC#3]
Great work!

I want to reproduce the results of SiameseXML on the dataset Q2BP,  how can I get this dataset?

And, it would be nice if the "Appendix" of the paper could be downloaded (only the main body of the paper, excluding the appendices in [here](https://www.cse.iitd.ac.in/~kunal/siamesexml_main.pdf).

Looking forward to the reply, ^^.

**Comment by kunaldahiya** [comment]
Hi,

Thanks for the interest. We'll be releasing the appendix and code after the conference. 

Q2BP is a proprietary dataset, i.e., we are not allowed to release it in the public domain. You should check out The Extreme Classification Repository for publicly available datasets.
